env:
  es2021: true
  node: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
rules:
  indent: ["error", 4]
  "import/first": ["off", ""]
  "@typescript-eslint/indent": ["error", 4]
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/naming-convention": off
  "@typescript-eslint/no-misused-promises": off
  "@typescript-eslint/no-confusing-void-expression": off
  "@typescript-eslint/strict-boolean-expressions": off,
  "@typescript-eslint/ban-ts-comment": off,