packages:
  - apps/*
  - functions
  - '!**/test/**'
  - '!**/tests/**'

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - '@firebase/util'
  - cypress
  - esbuild
  - fsevents
  - protobufjs
  - puppeteer
  - vue-demi
