name: AI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions: write-all

env:
  TZ: Europe/Stockholm

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: freeedcom/ai-codereviewer@v2.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
