name: Weekly Image Cleanup

on:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight
  workflow_dispatch:

env:
  GCLOUD_PROJECT: nackswinget-af7ef
  GCLOUD_REGION: europe-north1
  TZ: Europe/Stockholm

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup gcloud Cloud SDK auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/560237127162/locations/global/workloadIdentityPools/github-deployer-auth-pool/providers/github-deployer-auth-provider"
          service_account: "github-deployer-account@nackswinget-af7ef.iam.gserviceaccount.com"

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup default project (${{ env.GCLOUD_PROJECT }})
        run: gcloud config set project "${GCLOUD_PROJECT}"

      - name: Run clean up
        working-directory: ./functions
        run: ./clean-artifacts.sh
